# Generated by Django 5.1.6 on 2025-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('inprogress', 'In Progress'), ('pending', 'Pending'), ('blocker', 'Blocker')], default='pending', max_length=20),
        ),
    ]
